#actuator
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
