apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: movie-trailer-searcher-backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: api_username
              valueFrom:
                secretKeyRef:
                  key: username
                  name: backend-api
            - name: api_password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: backend-api
          name: backend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic dXNlcjpwYXNzd29yZA== #TODO change
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 120
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic dXNlcjpwYXNzd29yZA== #TODO change
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              name: backend
