apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: backend